import { StyleSheet } from 'react-native'

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0d0d1a' },
  hdr: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 4,
  },
  logoRow: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 8 },
  logo: { color: '#fff', fontSize: 24, fontWeight: '800' },
  cnt: { color: '#555', fontSize: 13 },
  newRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#222',
  },
  inp: {
    flex: 1,
    backgroundColor: '#1e1e2e',
    color: '#fff',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#333',
    marginRight: 8,
  },
  addBtn: {
    backgroundColor: '#6c63ff',
    borderRadius: 10,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  addTxt: { color: '#fff', fontWeight: '700', fontSize: 14 },
  list: { paddingVertical: 8, paddingHorizontal: 12 },
  card: {
    backgroundColor: '#1e1e2e',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
    borderWidth: 1,
    borderColor: '#2a2a3e',
  },
  cardBody: { flex: 1 },
  cardTitle: { color: '#fff', fontSize: 15, fontWeight: '600' },
  cardMeta: { color: '#555', fontSize: 12, marginTop: 3 },
  del: { padding: 6 },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyIco: { marginBottom: 12 },
  emptyMsg: { color: '#555', fontSize: 15, textAlign: 'center', lineHeight: 22 },
})
